### ISSUE TITLE
 Whether the widget can be supported

### ISSUE THREAD

**Issue by IF-tiger** [doncsugar/lightly-plasma#2]
![image](https://user-images.githubusercontent.com/60809013/186053460-c15eac81-656d-4c44-b873-38ee61edb8d9.png)
![image](https://user-images.githubusercontent.com/60809013/186053527-ebe5d245-2584-4ffb-997b-970ebb3ed930.png)
I like this hover effect, can you support the widget,thanks

**Comment by doncsugar** [comment]
Hello,

I generally try to do things the way Lightly does. It looks like this is how it is supposed to be:
![image](https://user-images.githubusercontent.com/46570709/186540732-144929a0-1580-403a-be53-1f1392b3cdbb.png)

It may not look very good, but I also added what you asked as an alternative. Drop it into `widgets/` in your equipped theme and reapply. Try it here: https://github.com/doncsugar/lightly-plasma/tree/main/src/willow-extras

**Comment by IF-tiger** [comment]
thanks
